### ISSUE TITLE
Suggestions for choosing test length are not clear

### ISSUE THREAD

**Issue by rbcavanaugh** [rbcavanaugh/acom#3]
- Currently in the technical documentation and a hidden tool-tip. Need to expose suggestions. 

@william-hula Do you think you could provide a couple succinct bullet points for choosing test length, perhaps broken down by research vs. clinical use?

**Comment by william-hula** [comment]
Yes, working on this now. Basically the test-retest reliability of the full test is decent at 0.9, but the 12-item CAT is kind of shit at 0.72. I'm working in running a quick simulation to see what you get with a couple of points in between (e.g., 25, 38, 50) to provide better guidance) I'll abandon this idea if it takes me longer than 24 hours to get these bullet points together.

From: Rob Cavanaugh ***@***.***>
Sent: Sunday, July 24, 2022 9:27 AM
To: rbcavanaugh/acom ***@***.***>
Cc: Hula, William D ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [rbcavanaugh/acom] Suggestions for choosing test length are not clear (Issue #3)


  *   Currently in the technical documentation and a hidden tool-tip. Need to expose suggestions.

@william-hula<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwilliam-hula&data=05%7C01%7C%7Ca391556ad1e54837bdc808da6d782d5f%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637942661854015072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TjDIppXw3ahyk0oGEzVwOMpGqRvFrrfUrrnXdg%2FEOec%3D&reserved=0> Do you think you could provide a couple succinct bullet points for choosing test length, perhaps broken down by research vs. clinical use?

-

**Comment by rbcavanaugh** [comment]
Closed with 4.0.2
